### ISSUE TITLE
problem getting correct results for d>1 in KRR_Standard

### ISSUE THREAD

**Issue by ahbarnett** [jiechenjiechen/RLCM#2]
Dear Jie,
I am stuck on something. As you suggested, I wrote a new driver based upon KRR_Standard, to make sure that this works as expected. My new executable is called `KRR_Standard_basicGP_IO_IsotropicGaussian_DPoint.ex` and has a different argument list from yours, and does I/O to simple binary files.
The problem I am stuck on is that the results of your KRR_Standard library calls match my own in d=1, but are wrong for d=2 and 3. This is for the squared-exp kernel, as simple as possible.
I am not even attempting KRR_RLCM yet, since I want the Standard to work first.
I have placed a minimal demo of this failure in my fork, which you need to call from MATLAB.
Simply:
1) from RLCM, rerun your `./configure.sh && make && make install && make apps`
This should compile
https://github.com/ahbarnett/RLCM/blob/master/app/KRR/KRR_Standard_basicGP_IO.cpp
into the above executable.
2) Open MATLAB from `ahb_try`, and run `RLCM`.

This produces the following, showing matching for d=1, and O(1) errors otherwise.
Is somehow your definition of the SE kernel different from mine? I don't see a difference
between my
https://github.com/ahbarnett/RLCM/blob/28a7b044c24cbcb1df23348202ea23969d70a27d/ahb_try/SE_ker.m#L20
and your
https://github.com/ahbarnett/RLCM/blob/28a7b044c24cbcb1df23348202ea23969d70a27d/src/Kernels/IsotropicGaussian.tpp#L14
I have also checked that all coords are correctly transferred from MATLAB to C++.

So, I am stuck, and cannot use RLCM until we resolve this. Could you kindly help?
Thanks so much,   Alex

```
>> RLCM

test RLCM, sigma=0.3, tol=1e-08, dim=1...
cmd =
    '/home/alex/SCDA/nufft/GP/RLCM/ahb_try/../app/KRR/KRR_Standard_basicGP_IO_IsotropicGaussian_DPoint.ex 1 3000 /tmp/RLCM_train_1.tmp 3000 /tmp/RLCM_xtest_1.tmp /tmp/RLCM_ypred_1.tmp 1 0.1 1 0.09'
	KRR_Standard.Train: (Ntrain=3000, dim=1) param = 0.1 0.09, time = 0.38071, mem_per_pt = 3000
	KRR_Standard.Test: (Ntest=3000) time = 0.121252
first 10 entries of y.mean vec and ytrue.mean vec...
         0.366847754133725         0.367145291748308
         0.370547087672024         0.370837553334943
          0.37520825107475         0.375489927979575
         0.378663261212711         0.378938510535583
           0.3797170042404         0.379990307844588
         0.390639897424022         0.390893430260874
         0.397639736316758         0.397880975734319
         0.402308069582205         0.402541271035719
         0.404207739441248          0.40443770649209
         0.405428859825185         0.405656758853525
CPU time (s):	0.518
y.mean: rms err vs meas data   0.295	(should be about sigmadata=0.3)
        rms truemeas pred err  0.0239	(should be sqrt(l^d.N) better ~ 0.017)
        rms RLCM vs naive      3.73e-05

test RLCM, sigma=0.3, tol=1e-08, dim=2...
cmd =
    '/home/alex/SCDA/nufft/GP/RLCM/ahb_try/../app/KRR/KRR_Standard_basicGP_IO_IsotropicGaussian_DPoint.ex 1 3000 /tmp/RLCM_train_1.tmp 3000 /tmp/RLCM_xtest_1.tmp /tmp/RLCM_ypred_1.tmp 2 0.1 1 0.09'
	KRR_Standard.Train: (Ntrain=3000, dim=2) param = 0.1 0.09, time = 0.385456, mem_per_pt = 3000
	KRR_Standard.Test: (Ntest=3000) time = 0.11674
first 10 entries of y.mean vec and ytrue.mean vec...
        -0.237569061696069          0.30616511604962
        0.0931931892265118        -0.531986423634179
        0.0522176632683061         0.525603509305303
        -0.225184335323018         0.847335958234974
        0.0670880486146888        -0.471709522238732
         0.171300632906097         0.750620283408836
         0.040319174014834        -0.942975386413074
       -0.0874357277497464         0.194533788133371
         -0.17779954998737       -0.0787200862456993
         0.116043388013733        -0.911767966743128
CPU time (s):	0.515
y.mean: rms err vs meas data   0.742	(should be about sigmadata=0.3)
        rms truemeas pred err  0.688	(should be sqrt(l^d.N) better ~ 0.055)
        rms RLCM vs naive      0.683

test RLCM, sigma=0.3, tol=1e-08, dim=3...
cmd =
    '/home/alex/SCDA/nufft/GP/RLCM/ahb_try/../app/KRR/KRR_Standard_basicGP_IO_IsotropicGaussian_DPoint.ex 1 3000 /tmp/RLCM_train_1.tmp 3000 /tmp/RLCM_xtest_1.tmp /tmp/RLCM_ypred_1.tmp 3 0.1 1 0.09'
	KRR_Standard.Train: (Ntrain=3000, dim=3) param = 0.1 0.09, time = 0.442141, mem_per_pt = 3000
	KRR_Standard.Test: (Ntest=3000) time = 0.121289
first 10 entries of y.mean vec and ytrue.mean vec...
        0.0315381732127954       -0.0923312925893848
        -0.394665782408415        -0.663282952379154
          0.22492023317484         0.273207438216387
         -0.94857258512736         -1.00374827753336
        -0.151318893622393       -0.0824772232094837
        -0.113662667901492       -0.0451251698705105
        -0.304768843456755        0.0409434910128708
        -0.117261010411086         0.791035174555945
        -0.437946486912322        -0.950838044177422
        0.0379366613246334          1.00396612393408
CPU time (s):	0.577
y.mean: rms err vs meas data   0.625	(should be about sigmadata=0.3)
        rms truemeas pred err  0.597	(should be sqrt(l^d.N) better ~ 0.17)
        rms RLCM vs naive      0.587
>> 
```

**Comment by jiechenjiechen** [comment]
@ahbarnett From https://github.com/ahbarnett/RLCM/blob/master/app/KRR/KRR_Standard_basicGP_IO.cpp#L107, it appears that your DPointArray Xtrain is row-major; that is, Xtrain[0] to Xtrain[d-1] mean the first point. However, https://github.com/jiechenjiechen/RLCM/blob/master/src/Matrices/DPointArray.hpp#L140 indicates that DPointArray is column-major; that is, X[0] to X[N-1] store the first coordinate value of all points. Could you check if this confusion causes the problem?

**Comment by ahbarnett** [comment]
Dear Jie, Thanks - that fixed it! I hadn't spend enough time looking in your DPoint etc header definitions...
Best, Alex
